name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install nix
        uses: cachix/install-nix-action@v27

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: ./ci.sh ./dist

      - uses: ncipollo/release-action@v1
        name: Release
        with:
          omitBody: true
          omitName: true
          allowUpdates: true
          artifacts: ./dist/*
